version: '3.8'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: first_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: jj2hrme3g9
    ports:
      - "5432:5432"  
    networks:
      - app-network

  your-java-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://62.109.19.68:5432/first_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: jj2hrme3g9
    depends_on:
      - postgresql
    networks:
      - app-network

  emot-web-ui:
    restart: always
    build:
      context: ./vkr
    ports:
      - "4200:80"

networks:
  app-network:
    driver: bridge